application: gdn-quiz-experiments
version: 21
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /api/.*
  script: api.app
- url: /tasks/.*
  script: tasks.app
- url: /reports/.*
  script: reports.app
- url: /reports
  script: reports.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on